on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    # runs-on: ubuntu-latest
    steps:
      - name: Create release
        working-directory: ${{ runner.temp }}/katapult/out
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          gh release create ${{github.ref_name}} --title "${{github.ref_name}}"