name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    # runs-on: ubuntu-latest
    steps:
      - name: Create release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          gh release create "${{github.ref_name}}" --repo "${{github.repository}}" --title "${{github.ref_name}}" --draft --notes "Release ${{github.ref_name}}"